server:
  port: 8080
  
logging:
  level[com.cegedim.academy]: DEBUG
  level[org.springframework.web]: DEBUG

spring:
  jpa:
    open-in-view: false
    database: default
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./db/server;AUTO_SERVER=TRUE;
    username: sa
    password: 